# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/tianyi/capstone/capstone.srcs/sources_1/bd/capstone/ip/capstone_debug_bridge_0_0/bd_0/ip/ip_0/constraints/axi_jtag.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_43ca_axi_jtag_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/tianyi/capstone/capstone.srcs/sources_1/bd/capstone/ip/capstone_debug_bridge_0_0/bd_0/ip/ip_0/bd_43ca_axi_jtag_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_43ca_axi_jtag_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/tianyi/capstone/capstone.srcs/sources_1/bd/capstone/ip/capstone_debug_bridge_0_0/bd_0/ip/ip_0/constraints/axi_jtag.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_43ca_axi_jtag_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/tianyi/capstone/capstone.srcs/sources_1/bd/capstone/ip/capstone_debug_bridge_0_0/bd_0/ip/ip_0/bd_43ca_axi_jtag_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_43ca_axi_jtag_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
