# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tianyi/capstone/capstone.srcs/sources_1/bd/capstone/ip/capstone_debug_bridge_0_0/capstone_debug_bridge_0_0.xci
# IP: The module: 'capstone_debug_bridge_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/tianyi/capstone/capstone.srcs/sources_1/bd/capstone/ip/capstone_debug_bridge_0_0/bd_0/bd_43ca.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_43ca || ORIG_REF_NAME==bd_43ca} -quiet] -quiet

# IP: /home/tianyi/capstone/capstone.srcs/sources_1/bd/capstone/ip/capstone_debug_bridge_0_0/bd_0/ip/ip_0/bd_43ca_axi_jtag_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_43ca_axi_jtag_0 || ORIG_REF_NAME==bd_43ca_axi_jtag_0} -quiet] -quiet

# IP: /home/tianyi/capstone/capstone.srcs/sources_1/bd/capstone/ip/capstone_debug_bridge_0_0/bd_0/ip/ip_1/bd_43ca_bsip_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_43ca_bsip_0 || ORIG_REF_NAME==bd_43ca_bsip_0} -quiet] -quiet

# XDC: /home/tianyi/capstone/capstone.srcs/sources_1/bd/capstone/ip/capstone_debug_bridge_0_0/bd_0/bd_43ca_ooc.xdc

# XDC: /home/tianyi/capstone/capstone.srcs/sources_1/bd/capstone/ip/capstone_debug_bridge_0_0/capstone_debug_bridge_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'capstone_debug_bridge_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/tianyi/capstone/capstone.srcs/sources_1/bd/capstone/ip/capstone_debug_bridge_0_0/capstone_debug_bridge_0_0.xci
# IP: The module: 'capstone_debug_bridge_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/tianyi/capstone/capstone.srcs/sources_1/bd/capstone/ip/capstone_debug_bridge_0_0/bd_0/bd_43ca.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_43ca || ORIG_REF_NAME==bd_43ca} -quiet] -quiet

# IP: /home/tianyi/capstone/capstone.srcs/sources_1/bd/capstone/ip/capstone_debug_bridge_0_0/bd_0/ip/ip_0/bd_43ca_axi_jtag_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_43ca_axi_jtag_0 || ORIG_REF_NAME==bd_43ca_axi_jtag_0} -quiet] -quiet

# IP: /home/tianyi/capstone/capstone.srcs/sources_1/bd/capstone/ip/capstone_debug_bridge_0_0/bd_0/ip/ip_1/bd_43ca_bsip_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_43ca_bsip_0 || ORIG_REF_NAME==bd_43ca_bsip_0} -quiet] -quiet

# XDC: /home/tianyi/capstone/capstone.srcs/sources_1/bd/capstone/ip/capstone_debug_bridge_0_0/bd_0/bd_43ca_ooc.xdc

# XDC: /home/tianyi/capstone/capstone.srcs/sources_1/bd/capstone/ip/capstone_debug_bridge_0_0/capstone_debug_bridge_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'capstone_debug_bridge_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
