# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/capstone/capstone.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==capstone || ORIG_REF_NAME==capstone} -quiet] -quiet

# IP: bd/capstone/ip/capstone_axistream_packetfilt_0_0/capstone_axistream_packetfilt_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==capstone_axistream_packetfilt_0_0 || ORIG_REF_NAME==capstone_axistream_packetfilt_0_0} -quiet] -quiet

# IP: bd/capstone/ip/capstone_zynq_ultra_ps_e_0_0/capstone_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==capstone_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==capstone_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/capstone/ip/capstone_smartconnect_0_0/capstone_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==capstone_smartconnect_0_0 || ORIG_REF_NAME==capstone_smartconnect_0_0} -quiet] -quiet

# IP: bd/capstone/ip/capstone_axi_fifo_mm_s_0_0/capstone_axi_fifo_mm_s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==capstone_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==capstone_axi_fifo_mm_s_0_0} -quiet] -quiet

# IP: bd/capstone/ip/capstone_debug_bridge_0_0/capstone_debug_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==capstone_debug_bridge_0_0 || ORIG_REF_NAME==capstone_debug_bridge_0_0} -quiet] -quiet

# IP: bd/capstone/ip/capstone_system_ila_0_0/capstone_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==capstone_system_ila_0_0 || ORIG_REF_NAME==capstone_system_ila_0_0} -quiet] -quiet

# IP: bd/capstone/ip/capstone_xlconstant_0_0/capstone_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==capstone_xlconstant_0_0 || ORIG_REF_NAME==capstone_xlconstant_0_0} -quiet] -quiet

# IP: bd/capstone/ip/capstone_input_0_0/capstone_input_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==capstone_input_0_0 || ORIG_REF_NAME==capstone_input_0_0} -quiet] -quiet

# XDC: bd/capstone/capstone_ooc.xdc
